version: "3.8"

services:
  app:
    image: rupamjyotiborahaws/cakebox:latest
    container_name: cakebox-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./.env:/var/www/html/.env
    depends_on:
      - mysql
    networks:
      - cakebox-net

  mysql:
    image: mysql:8.0
    container_name: cakebox-mysql
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakebox
      MYSQL_USER: cakebox
      MYSQL_PASSWORD: cakebox!2025
    ports:
      - "3306:3306"
    volumes:
      - cakeboxdbdata:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - cakebox-net

volumes:
  cakeboxdbdata:

networks:
  cakebox-net:
