version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: DockerfileLocal
    container_name: cakebox-app
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
      - ./storage:/var/www/html/storage
      - ./bootstrap:/var/www/html/bootstrap
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - mysql
    environment:
      APP_ENV: local
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: cakebox
      DB_USERNAME: cakebox
      DB_PASSWORD: cakebox!2025 
    networks:
      - cakebox-net

  mysql:
    image: mysql:8.0
    container_name: cakebox-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakebox
      MYSQL_USER: cakebox
      MYSQL_PASSWORD: cakebox!2025
    ports:
      - "3307:3306"
    volumes:
      - cakeboxdbdata:/var/lib/mysql
    networks:
      - cakebox-net

volumes:
  cakeboxdbdata:

networks:
  cakebox-net:
