version: "3.8"

services:
  app:
    image: rupamjyotiborahaws/cakebox:latest
    #container_name: cakebox-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      #- ./public:/var/www/html/public
      #- ./storage:/var/www/html/storage
      #- ./bootstrap:/var/www/html/bootstrap
      - /etc/letsencrypt:/etc/letsencrypt:ro
      #- .:/var/www/html/
      - ./.env:/var/www/html/.env
    depends_on:
      - mysql
    #environment:
      #DB_CONNECTION: mysql
      #DB_HOST: mysql
      #DB_PORT: 3306
      #DB_DATABASE: cakebox
      #DB_USERNAME_FILE: /run/secrets/cb_db_username
      #DB_PASSWORD_FILE: /run/secrets/cb_db_password
    #secrets:
     # - cb_db_username
     # - cb_db_password
    networks:
      - cakebox-net

  mysql:
    image: mysql:8.0
    #container_name: cakebox-mysql
    #restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakebox
      MYSQL_USER: cakebox
      MYSQL_PASSWORD: cakebox!2025
    ports:
      - "3306:3306"
    volumes:
      - cakeboxdbdata:/var/lib/mysql
    networks:
      - cakebox-net

volumes:
  cakeboxdbdata:

#secrets:
  #cb_db_username:
    #external: true
  #cb_db_password:
    #external: true

networks:
  cakebox-net:
