name: Build, Push and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t rupamjyotiborahaws/cakebox:latest .

      - name: Push Docker image
        run: |
          docker push rupamjyotiborahaws/cakebox:latest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/rupamjyotiborahaws/projects/cakebox
            git pull origin master
            docker pull rupamjyotiborahaws/cakebox:latest
            docker-compose up -d --force-recreate
            until docker exec cakebox-app mysqladmin ping -hmysql -ucakebox -pcakebox!2025 --silent; do
              echo "Waiting for MySQL to be ready..."
              sleep 5
            done
            docker exec cakebox-app php artisan migrate --force
